### ISSUE TITLE
Downloading Forge Files Fails

### ISSUE THREAD

**Issue by DomAmato** [tomsik68/mclauncher-api#28]
Here is the code that is problematic:

```
YDLoginService loginService = new YDLoginService();
			IProfile profile = new LegacyProfile(username, password);
			ISession session = loginService.login(profile);

			monitor.setStatus("Success! Launching...");

			String path = Platform.getCurrentPlatform().getWorkingDirectory().getAbsolutePath();
			final MinecraftInstance mc = new MinecraftInstance(Platform.getCurrentPlatform().getWorkingDirectory());
			// lets get the forge json file
			File file = new File(path + "/versions/forge/forge.json");
			monitor.setStatus("Installing Forge");
			MCFileUtils.downloadFileWithProgress("link/to/forgejson/location/forge.json",
					file, monitor);

			// this will install the forge and vanilla client
			MCDownloadVersionList versionList = new MCDownloadVersionList(mc);
			IVersion toLaunch = versionList.retrieveVersionInfo("forge");
			toLaunch.getInstaller().install(toLaunch, mc, monitor);
```

The reason is the forge files are sometimes in a packed format and the main jar url is actually different than what your api sets it to. I did a really ugly and quick patch to make it work which is here:

https://github.com/CityOfLearning/mclauncher-api/blob/dyn/tomsik68/mclauncher/util/MCFileUtils.java#L116-L125

really what I should do is get the proper link from the forge method using this: https://github.com/MinecraftForge/Installer/blob/master/src/main/java/net/minecraftforge/installer/Artifact.java

But I just wanted to raise it to your attention as well :smile:

**Comment by DomAmato** [comment]
its pretty easy if you use their artifact.java class I linked, when you call the getPath function it parses out the path needed to download the file. You just pass it the maven-esqe descriptor e.g. net.minecraft:launchwrapper:1.11 and it will determine the proper path of the download.

**Comment by tomsik68** [comment]
I checked some aspects of this issue and I figured out this is not a bug in mclauncher-api. Official launcher is not able to download minecraftforge files either. minecraftforge library is meant to be installed via official minecraftforge installer. I tested by removing `net/minecraftforge` from my libraries folder and launching via official launcher and this is the error I've got:
```
[15:40:52 WARN]: Couldn't download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.9-12.16.1.1887/forge-1.9-12.16.1.1887.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 404
	at com.mojang.launcher.updater.download.ChecksummedDownloadable.download(ChecksummedDownloadable.java:97) ~[launcher.jar:1.6.61]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:109) [launcher.jar:1.6.61]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.61]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.61]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

I recommend sticking to official minecraftforge installer(https://github.com/MinecraftForge/Installer) for version installation. If you want, it might be possible to bundle it with your launcher and use the correct methods to install forge before launching minecraft via mclauncher-api.
