### ISSUE TITLE
Can't download Minecraft 1.12.2

### ISSUE THREAD

**Issue by FollowTM** [tomsik68/mclauncher-api#47]
When I'm trying to run method `minecraftLauncherBackend.updateMinecraft("1.12.2", null);`
I've got this error.

Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.Artifact.fromJson(Artifact.java:21)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.Library.<init>(Library.java:44)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersion.<init>(MCDownloadVersion.java:78)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadOnlineVersionList.retrieveVersionInfo(MCDownloadOnlineVersionList.java:50)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.retrieveVersionInfo(MCDownloadVersionList.java:44)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.findVersion(MinecraftLauncherBackend.java:29)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.updateMinecraft(MinecraftLauncherBackend.java:61)
	at mpeciakk.launcher.Main.main(Main.java:24)

**Comment by tomsik68** [comment]
Hi, thanks for the error report! Which API version are you using?

**Comment by tomsik68** [comment]
Ok, I think I found the problem. As opposed to what the API assumes, the `artifact` field within a library is not required. Minecraft version `1.12.2` has a library without it apparently. So the assumptions need to change.

**Comment by tomsik68** [comment]
Thanks for the error report again. I was able to download & launch Minecraft 1.12.2 from OneClickMC, so the issue should be solved by now. Fixed version of the API has been published to maven as `0.3.3`. If it still doesn't work for you, feel free to reopen this issue.
