### ISSUE TITLE
Failed to launch forge

### ISSUE THREAD

**Issue by JakobDev** [tomsik68/mclauncher-api#54]
I call MinecraftLauncherBackend.launchMinecraft with 1.12.2-forge1.12.2-14.23.3.2678 as VersionId, it will crash with this stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.Artifact.fromJson(Artifact.java:21)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersion.fromJson(MCDownloadVersion.java:112)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadLocalVersionList.retrieveVersionInfo(MCDownloadLocalVersionList.java:58)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.retrieveVersionInfo(MCDownloadVersionList.java:42)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.findVersion(MinecraftLauncherBackend.java:29)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.launchMinecraft(MinecraftLauncherBackend.java:89)
	at jakobdev.mclauncher_cmd.mclauncher_cmd.main(mclauncher_cmd.java:18)
```
If I call it with 1.14.3 or 1.12.2 as Version ID everything works great. Forge works in the normal Minecraft Launcher, so it should be installed correctly.

**Comment by tomsik68** [comment]
I think this should already be fixed in the latest version. Good thing you reminded me I didn't release it here on github :smile:

Are you using version 0.3.4? You can download the latest jar from my maven repo: https://raw.githubusercontent.com/tomsik68/maven-repo/master/sk/tomsik68/mclauncher-api/0.3.4/mclauncher-api-0.3.4.jar

**Comment by JakobDev** [comment]
I'm already using 0.3.4

**Comment by tomsik68** [comment]
Thanks for the clarification. I'll test it myself.

**Comment by tomsik68** [comment]
So I just launched Minecraft `1.12.2-forge1.12.2-14.23.5.2768` successfully. It could be an issue with that particular version you're using.

I can't find download Forge 14.23.3 anywhere. Could you please pastebin the json file you're using? Or provide a link to forge installer, so I can try it myself?

**Comment by JakobDev** [comment]
[Link to json](https://pastebin.com/MYKUaSba)

This Forge Version is very long on my Computer. I will look, if I can find the installer.
