### ISSUE TITLE
Unable to install old versions

### ISSUE THREAD

**Issue by JakobDev** [tomsik68/mclauncher-api#57]
It is not possible to install old versions like a1.1.2 or b1.2.

**Comment by JakobDev** [comment]
@tomsik68 Will this issue be fixed?

**Comment by JakobDev** [comment]
@tomsik68 
It still gives me a error:
```
jakob@Pluto:~/zw/mclauncher-cmd/out/artifacts/mclauncher_cmd_jar$ java -jar mclauncher-cmd.jar install a1.1.2 /home/jakob/.minecraft/
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.Artifact.fromJson(Artifact.java:21)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersion.fromJson(MCDownloadVersion.java:113)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadOnlineVersionList.retrieveVersionInfo(MCDownloadOnlineVersionList.java:50)
	at sk.tomsik68.mclauncher.impl.versions.mcdownload.MCDownloadVersionList.retrieveVersionInfo(MCDownloadVersionList.java:44)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.findVersion(MinecraftLauncherBackend.java:29)
	at sk.tomsik68.mclauncher.backend.MinecraftLauncherBackend.updateMinecraft(MinecraftLauncherBackend.java:61)
	at main.java.jakobdev.mclauncher_cmd.mclauncher_cmd.main(mclauncher_cmd.java:27)
```

**Comment by tomsik68** [comment]
Interesting, I can't reproduce the error with mclauncher-api version 0.3.6. The issue is, that the `downloads` section doesn't contain any `server` artifact. However, the newest version checks if the artifact is present before trying to parse it.

Could you, please, recompile mclauncher-cmd.jar with mclauncher-api 0.3.6 and try again ? 
You can find the jar file here: https://github.com/tomsik68/maven-repo/blob/master/sk/tomsik68/mclauncher-api/0.3.6/mclauncher-api-0.3.6.jar?raw=true

**Comment by JakobDev** [comment]
It looks like the problem is IntelliJ. If I run the programm from IntelliJ it works, but if I built a JAR File, I get the error. Do you now the reason for that?

btw:
My source code is [here](https://gitlab.com/JakobDev/mclauncher-cmd)

**Comment by tomsik68** [comment]
The problem could be the way you build the JAR. It looks like older version of the API is built into the JAR, but IntelliJ uses the newest version to run it.
